{% set name = "yargy" %}
{% set version = "0.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yargy-{{ version }}.tar.gz
  sha256: c917eefb32a40c23c46b6ca88d68927072dd00ab94e90fd5dc6ab0a62b59b593

build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pymorphy2
    - python

test:
  imports:
    - yargy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/natasha/yargy
  summary: Rule-based facts extraction for Russian language
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - harri-pltr
